### PR TITLE
[FIX]:Fixed the Features element in navbar to navigate to the listed features  

### PR DESCRIPTION
**Pull request by RAVEYUS**
This PR address issue #23 , in which the features element was causing the re-render of the entire landing page, the issue has been resolved with the usage of <Link/> tags instead of <a/>.

### CODE REVIEW

**Comment by sahilrohera10** [comment]
@RAVEYUS Has this issue been assigned to you ??

**Comment by RAVEYUS** [comment]
@sahilrohera10 No, but I was able to figure out the issue and hence the PR.

**Comment by sahilrohera10** [comment]
Well, from next time, try to get it assigned on your name 
have you tested the functionality ?
@RAVEYUS

**Comment by RAVEYUS** [comment]
@sahilrohera10 Yes I have

**Comment by sahilrohera10** [comment]
since its a dynamic functionality, can we have a quick short video for this. @RAVEYUS

**Comment by RAVEYUS** [comment]
@sahilrohera10  Here you go
https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/135033576/fb4961dc-1410-413d-b03e-d45dab5fb197

**Comment by sahilrohera10** [comment]
@RAVEYUS okay great, i will check with the already assigned person for this issue once, if there is no update from her, then i will merge the PR.

keep contributing and explore the platform after login, and must get assigned the issue on your name before starting the work.

**Comment by SnipSavvy** [comment]
@RAVEYUS add a comment on the issue .. that i have resolved this issue so please assign this to me .. so that i can assign you!

**Comment by RAVEYUS** [comment]
@SnipSavvy made the comment do check it, thanks.

**Pull request merged**
